// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdvvjmcqnzbcyrqlritk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkdnZqbWNxbnpiY3lycWxyaXRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1NzE1MTQsImV4cCI6MjA3NjE0NzUxNH0.-hl0EFH3UZ8Lh2kwjwYACoyk-5PKRQJB32AjALC4XH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});